version: '{branch}-{build}'
init:
- cmd: git config --global core.autocrlf true
before_build:
- cmd: >-
    git submodule update --init --recursive

    nuget restore CSF.Security.sln
build:
  project: CSF.Security.sln
  verbosity: normal